### ISSUE TITLE
JDK9 requires that local management agent be started

### ISSUE THREAD

**Issue by nlwillia** [nickman/jmxlocal#3]
The JDK9 [release notes](http://www.oracle.com/technetwork/java/javase/9-removed-features-3745614.html#JDK-8043939) explain that tools that use the Attach API need to make a call to start calling `com.sun.tools.attach.VirtualMachine.startManagementAgent(Properties agentProperties)` on the target before making a connection.

If you don't, then jmxlocal will fail with something resembling the following.
```
Caused by: java.lang.RuntimeException: Failed to acquire JMXServiceURL from VirtualMachine [7004]
	at com.heliosapm.shorthand.attach.vm.VirtualMachine.getJMXServiceURL(VirtualMachine.java:377)
	at com.heliosapm.shorthand.attach.vm.VirtualMachine.getJMXConnector(VirtualMachine.java:347)
	... 7 more
Caused by: com.heliosapm.shorthand.attach.vm.VirtualMachineInvocationException: Failed to invoke [public void com.sun.tools.attach.VirtualMachine.loadAgent(java.lang.String) throws com.sun.tools.attach.AgentLoadException,com.sun.tools.attach.AgentInitializationException,java.io.IOException]
	at com.heliosapm.shorthand.attach.vm.BaseWrappedClass.invoke(BaseWrappedClass.java:107)
	at com.heliosapm.shorthand.attach.vm.VirtualMachine.loadAgent(VirtualMachine.java:254)
	at com.heliosapm.shorthand.attach.vm.VirtualMachine.getJMXServiceURL(VirtualMachine.java:370)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.heliosapm.shorthand.attach.vm.BaseWrappedClass.invoke(BaseWrappedClass.java:105)
	... 10 more
Caused by: com.sun.tools.attach.AgentLoadException: Agent JAR not found or no Agent-Class attribute
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:151)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:538)
	... 15 more
```
I was able to get it to work in a test client program with the following at the beginning:
```
for (com.sun.tools.attach.VirtualMachineDescriptor vmd : com.sun.tools.attach.VirtualMachine.list()) {
	com.sun.tools.attach.VirtualMachine.attach(vmd).startLocalManagementAgent();
}
```
After that, jmxlocal could connect fine.  But it would obviously be better if it could abstract this for the caller and limit it to the specific VM you want to talk to.

**Comment by nlwillia** [comment]
Adding a line to the [VirtualMachine](https://github.com/nickman/jmxlocal/blob/master/src/main/java/com/heliosapm/shorthand/attach/vm/VirtualMachine.java#L94) constructor seems to take care of it.
```
	VirtualMachine(Object delegate) {
		super(delegate);
		invoke(delegate, VirtualMachineBootstrap.VM_CLASS, "startLocalManagementAgent");
	}
```
I tested w/Java 8-10.  I expected it to break under 8, but I guess the method is present at that level but undocumented.  For older support it might have to allow for the method not existing.

**Comment by nickman** [comment]
Hello Nathan;
Thanks for opening a ticket.
I have applied your recommended patch in the branch **JDK9**.
Could you give it a spin ?
Thanks.
//Nicholas

**Comment by nlwillia** [comment]
Works well, thanks!

**Comment by slyns** [comment]
would it be possible to publish jmxlocal:1.1 to Maven Central?
